/**
 * openapiPaths.generated.ts — OpenAPI 3.0 `paths` entries for the ~170 non-core REST routes
 * of HttpRelayService (Boss relay server). Auto-generated by mechanically walking:
 *   - HttpRelayService.ts: handleRestApi() (GET /api/query/*, /api/boot, /api/search/*,
 *     POST /api/command/ai/chat|suggest, /api/library/*) and executeRestCommand()
 *     (POST/PUT/PATCH/DELETE /api/command/*).
 *   - handlers/RestApiHandlers.ts: query-param usage per handler (params.xxx / error('Missing xxx')).
 *   - handlers/LibraryHandler.ts + handlers/MediaHandler.ts: /api/library/* and /api/media/*.
 *
 * The 8 "core" endpoints (auth/proxy/sync/media-upload/health/SSE) are hand-written in
 * ./openapiSpec.ts and are intentionally NOT duplicated here.
 *
 * Do not hand-edit — if a route is added/changed in HttpRelayService.ts, regenerate this file.
 *
 * Response bodies use a shared generic envelope (#/components/schemas/ApiResponse, declared in
 * openapiSpec.ts) rather than per-field JSON Schema — this file prioritizes exhaustive ROUTE
 * coverage over deep response-shape typing.
 */

type OpenApiOperation = Record<string, any>;

const BEARER_SECURITY = [{ bearerAuth: [] }];
const NO_SECURITY: Array<Record<string, any>> = [];

const OK_RESPONSE = {
  description: 'OK',
  content: { 'application/json': { schema: { $ref: '#/components/schemas/ApiResponse' } } },
};
const UNAUTHORIZED_RESPONSE = { description: 'Unauthorized' };

/** Query or path parameter descriptor. */
function param(
  name: string,
  location: 'query' | 'path',
  type: string,
  opts: { required?: boolean; description?: string } = {}
): OpenApiOperation {
  const p: OpenApiOperation = {
    name,
    in: location,
    required: location === 'path' ? true : !!opts.required,
    schema: { type },
  };
  if (opts.description) p.description = opts.description;
  return p;
}

const qp = (name: string, type: string = 'string', required = false, description?: string) =>
  param(name, 'query', type, { required, description });
const pp = (name: string, type: string = 'string', description?: string) =>
  param(name, 'path', type, { description });

function requestBody(properties: Record<string, any>, required = true): OpenApiOperation {
  return {
    required,
    content: {
      'application/json': {
        schema: { type: 'object', properties },
      },
    },
  };
}

/**
 * Build one OpenAPI Operation Object.
 * `security: undefined` (default) → bearerAuth required, 401 documented.
 * `security: []` → unauthenticated (media/library file-serving — tunnel security only).
 */
function op(opts: {
  tags: string[];
  summary: string;
  operationId: string;
  security?: Array<Record<string, any>>;
  parameters?: OpenApiOperation[];
  requestBody?: OpenApiOperation;
}): OpenApiOperation {
  const security = opts.security !== undefined ? opts.security : BEARER_SECURITY;
  const isPublic = security.length === 0;
  const result: OpenApiOperation = {
    tags: opts.tags,
    summary: opts.summary,
    operationId: opts.operationId,
    security,
    responses: isPublic
      ? { '200': OK_RESPONSE }
      : { '200': OK_RESPONSE, '401': UNAUTHORIZED_RESPONSE },
  };
  if (opts.parameters && opts.parameters.length > 0) result.parameters = opts.parameters;
  if (opts.requestBody) result.requestBody = opts.requestBody;
  return result;
}

/** Merge one HTTP method's operation into the growing paths object (allows multiple methods per path). */
function addOp(
  paths: Record<string, any>,
  path: string,
  method: 'get' | 'post' | 'put' | 'patch' | 'delete',
  operation: OpenApiOperation
): void {
  if (!paths[path]) paths[path] = {};
  paths[path][method] = operation;
}

export const generatedPaths: Record<string, any> = (() => {
  const paths: Record<string, any> = {};

  // ═══════════════════════════════════════════════════════════════
  // BOOT
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/boot', 'get', op({
    tags: ['Boot'],
    summary: "Get initial bootstrap data (conversations, accounts, labels, quick messages, pinned conversations, drafts) for the employee's assigned account",
    operationId: 'getBoot',
  }));

  // ═══════════════════════════════════════════════════════════════
  // CONVERSATIONS (query)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/conversations', 'get', op({
    tags: ['Conversations'],
    summary: 'Get paginated conversations for the employee\'s assigned account',
    operationId: 'getConversations',
    parameters: [
      qp('zaloId', 'string', false, 'Defaults to first assigned account'),
      qp('limit', 'integer'), qp('offset', 'integer'), qp('search', 'string'),
    ],
  }));
  addOp(paths, '/api/query/conversations/updates', 'get', op({
    tags: ['Conversations'],
    summary: 'Get conversations updated since a given timestamp (incremental sync)',
    operationId: 'getConversationsUpdates',
    parameters: [qp('zaloId'), qp('sinceTs', 'integer'), qp('limit', 'integer')],
  }));
  addOp(paths, '/api/query/conversations/flags', 'get', op({
    tags: ['Conversations'],
    summary: 'Get per-contact flags (e.g. spam/blocked markers) for an account',
    operationId: 'getConversationFlags',
    parameters: [qp('zaloId', 'string', true)],
  }));
  addOp(paths, '/api/query/conversations/{contactId}', 'get', op({
    tags: ['Conversations'],
    summary: 'Get a single conversation/contact by id',
    operationId: 'getConversationById',
    parameters: [pp('contactId'), qp('zaloId')],
  }));

  // ═══════════════════════════════════════════════════════════════
  // MESSAGES (query)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/messages/around', 'get', op({
    tags: ['Messages'],
    summary: 'Get messages around a given message id (for jump-to-message)',
    operationId: 'getMessagesAround',
    parameters: [qp('zaloId'), qp('threadId', 'string', true), qp('msgId', 'string', true), qp('limit', 'integer')],
  }));
  addOp(paths, '/api/query/messages/file', 'get', op({
    tags: ['Messages'],
    summary: 'Get file-type messages in a thread, paginated',
    operationId: 'getFileMessages',
    parameters: [qp('zaloId'), qp('threadId', 'string', true), qp('limit', 'integer'), qp('offset', 'integer')],
  }));
  addOp(paths, '/api/query/messages/media', 'get', op({
    tags: ['Messages'],
    summary: 'Get media (image/video) messages, optionally scoped to a thread',
    operationId: 'getMediaMessages',
    parameters: [qp('zaloId'), qp('threadId'), qp('limit', 'integer'), qp('offset', 'integer')],
  }));
  addOp(paths, '/api/query/messages', 'get', op({
    tags: ['Messages'],
    summary: 'Get paginated messages for a thread (offset- or cursor-based via `before`)',
    operationId: 'getMessages',
    parameters: [
      qp('zaloId'), qp('threadId', 'string', true), qp('limit', 'integer'), qp('offset', 'integer'),
      qp('before', 'integer', false, 'Cursor timestamp — switches to cursor-based pagination'),
      qp('topicId'),
    ],
  }));
  addOp(paths, '/api/query/messages/{msgId}', 'get', op({
    tags: ['Messages'],
    summary: 'Get a single message by id',
    operationId: 'getMessageById',
    parameters: [pp('msgId'), qp('zaloId'), qp('threadId')],
  }));
  addOp(paths, '/api/query/messages/unread', 'get', op({
    tags: ['Messages'],
    summary: 'Get total unread message count for an account',
    operationId: 'getUnreadCountHandler',
    parameters: [qp('zaloId', 'string', true)],
  }));
  addOp(paths, '/api/query/messages/by-type', 'get', op({
    tags: ['Messages'],
    summary: 'Get messages of a specific msgType in a thread',
    operationId: 'getMessagesByTypeHandler',
    parameters: [qp('zaloId', 'string', true), qp('threadId', 'string', true), qp('msgType', 'string', true), qp('limit', 'integer')],
  }));
  addOp(paths, '/api/query/pinned-messages', 'get', op({
    tags: ['Messages'],
    summary: 'Get pinned messages in a thread',
    operationId: 'getPinnedMessages',
    parameters: [qp('zaloId', 'string', true), qp('threadId', 'string', true)],
  }));

  // ═══════════════════════════════════════════════════════════════
  // SEARCH
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/search/messages', 'get', op({
    tags: ['Search'],
    summary: 'Full-text search across messages for an account',
    operationId: 'searchMessages',
    parameters: [qp('zaloId', 'string', true), qp('q', 'string', true), qp('limit', 'integer')],
  }));

  // ═══════════════════════════════════════════════════════════════
  // FRIENDS (query)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/friends', 'get', op({
    tags: ['Friends'],
    summary: 'Get the friend list for an account',
    operationId: 'getFriends',
    parameters: [qp('zaloId', 'string', true)],
  }));
  addOp(paths, '/api/query/friends/check', 'get', op({
    tags: ['Friends'],
    summary: 'Check if a user is a friend of the account',
    operationId: 'getFriendCheck',
    parameters: [qp('zaloId', 'string', true), qp('userId', 'string', true)],
  }));
  addOp(paths, '/api/query/friends/last-fetched', 'get', op({
    tags: ['Friends'],
    summary: 'Get the last-fetched timestamp of the friend list',
    operationId: 'getFriendsLastFetchedHandler',
    parameters: [qp('zaloId', 'string', true)],
  }));

  // ═══════════════════════════════════════════════════════════════
  // FRIEND REQUESTS (query)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/friend-requests', 'get', op({
    tags: ['FriendRequests'],
    summary: 'Get sent/received friend requests for an account',
    operationId: 'getFriendRequests',
    parameters: [qp('zaloId', 'string', true), qp('direction', 'string', false, "'sent' | 'received'"), qp('limit', 'integer'), qp('offset', 'integer')],
  }));

  // ═══════════════════════════════════════════════════════════════
  // GROUPS (query)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/groups/members', 'get', op({
    tags: ['Groups'],
    summary: 'Get members of a specific group',
    operationId: 'getGroupMembers',
    parameters: [qp('zaloId', 'string', true), qp('groupId', 'string', true)],
  }));
  addOp(paths, '/api/query/groups/all', 'get', op({
    tags: ['Groups'],
    summary: 'Get all group memberships known for an account',
    operationId: 'getAllGroupMembers',
    parameters: [qp('zaloId', 'string', true)],
  }));

  // ═══════════════════════════════════════════════════════════════
  // CRM (query + command)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/crm/notes', 'get', op({
    tags: ['CRM'],
    summary: 'Get CRM notes for a contact',
    operationId: 'getCRMNotes',
    parameters: [qp('zaloId', 'string', true), qp('contactId', 'string', true)],
  }));
  addOp(paths, '/api/query/crm/campaigns', 'get', op({
    tags: ['CRM'],
    summary: 'Get CRM campaigns for an account',
    operationId: 'getCRMCampaigns',
    parameters: [qp('zaloId', 'string', true)],
  }));
  addOp(paths, '/api/query/crm/tags', 'get', op({
    tags: ['CRM'],
    summary: 'Get CRM tags for an account',
    operationId: 'getCRMTagsHandler',
    parameters: [qp('zaloId', 'string', true)],
  }));
  addOp(paths, '/api/query/crm/contacts', 'get', op({
    tags: ['CRM'],
    summary: 'Get CRM contacts with filters/pagination options',
    operationId: 'getCRMContactsHandler',
    parameters: [qp('zaloId', 'string', true), qp('opts', 'object', false, 'JSON-encoded filter/pagination options')],
  }));
  addOp(paths, '/api/query/crm/contacts/stats', 'get', op({
    tags: ['CRM'],
    summary: 'Get CRM contact statistics for an account',
    operationId: 'getContactStatsHandler',
    parameters: [qp('zaloId', 'string', true)],
  }));
  addOp(paths, '/api/query/crm/campaigns/contacts', 'get', op({
    tags: ['CRM'],
    summary: 'Get contacts attached to a campaign',
    operationId: 'getCampaignContactsHandler',
    parameters: [qp('campaignId', 'integer', true)],
  }));
  addOp(paths, '/api/query/crm/campaigns/send-log', 'get', op({
    tags: ['CRM'],
    summary: 'Get campaign send log entries',
    operationId: 'getSendLogHandler',
    parameters: [qp('zaloId', 'string', true), qp('opts', 'object', false, 'JSON-encoded filter options')],
  }));
  addOp(paths, '/api/query/crm/queue-status', 'get', op({
    tags: ['CRM'],
    summary: 'Get the CRM send-queue status (running state, remaining tokens) for an account',
    operationId: 'getQueueStatusHandler',
    parameters: [qp('zaloId', 'string', true)],
  }));
  addOp(paths, '/api/query/crm/campaigns/stats', 'get', op({
    tags: ['CRM'],
    summary: 'Get top campaign statistics for an account',
    operationId: 'getCampaignStatsHandler',
    parameters: [qp('zaloId', 'string', true), qp('limit', 'integer')],
  }));
  addOp(paths, '/api/query/crm/activity-stats', 'get', op({
    tags: ['CRM'],
    summary: 'Get CRM activity statistics over a time range',
    operationId: 'getActivityStatsHandler',
    parameters: [qp('zaloId', 'string', true), qp('sinceTs', 'integer'), qp('untilTs', 'integer')],
  }));

  addOp(paths, '/api/command/crm/notes', 'post', op({
    tags: ['CRM'],
    summary: 'Create or update a CRM note',
    operationId: 'saveCrmNote',
    requestBody: requestBody({ zaloId: { type: 'string' }, note: { type: 'object' } }),
  }));
  addOp(paths, '/api/command/crm/notes/{id}', 'delete', op({
    tags: ['CRM'],
    summary: 'Delete a CRM note',
    operationId: 'deleteCrmNote',
    parameters: [pp('id', 'integer'), qp('zaloId')],
  }));
  addOp(paths, '/api/command/crm/campaigns', 'post', op({
    tags: ['CRM'],
    summary: 'Create or update a CRM campaign',
    operationId: 'saveCrmCampaign',
    requestBody: requestBody({ zaloId: { type: 'string' }, campaign: { type: 'object' } }),
  }));
  addOp(paths, '/api/command/crm/campaigns/{id}', 'delete', op({
    tags: ['CRM'],
    summary: 'Delete a CRM campaign',
    operationId: 'deleteCrmCampaign',
    parameters: [pp('id', 'integer'), qp('zaloId')],
  }));
  addOp(paths, '/api/command/crm/campaigns/clone', 'post', op({
    tags: ['CRM'],
    summary: 'Clone an existing CRM campaign, optionally including its contacts',
    operationId: 'cloneCrmCampaign',
    requestBody: requestBody({ campaignId: { type: 'integer' }, includeContacts: { type: 'boolean' }, newName: { type: 'string' } }),
  }));
  addOp(paths, '/api/command/crm/campaigns/status', 'post', op({
    tags: ['CRM'],
    summary: 'Update a CRM campaign\'s status',
    operationId: 'updateCrmCampaignStatus',
    requestBody: requestBody({ campaignId: { type: 'integer' }, status: { type: 'string' } }),
  }));
  addOp(paths, '/api/command/crm/campaigns/contacts', 'post', op({
    tags: ['CRM'],
    summary: 'Add contacts to a campaign',
    operationId: 'addCampaignContacts',
    requestBody: requestBody({ campaignId: { type: 'integer' }, contacts: { type: 'array', items: { type: 'object' } } }),
  }));
  addOp(paths, '/api/command/crm/campaigns/contacts', 'delete', op({
    tags: ['CRM'],
    summary: 'Remove specific contacts from a campaign',
    operationId: 'removeCampaignContacts',
    requestBody: requestBody({ campaignId: { type: 'integer' }, contactIds: { type: 'array', items: { type: 'string' } } }),
  }));
  addOp(paths, '/api/command/crm/campaigns/contacts/all', 'delete', op({
    tags: ['CRM'],
    summary: 'Remove all contacts from a campaign (also reachable via POST for client compatibility)',
    operationId: 'deleteAllCampaignContacts',
    requestBody: requestBody({ campaignId: { type: 'integer' } }),
  }));
  addOp(paths, '/api/command/crm/campaigns/contacts/delete', 'post', op({
    tags: ['CRM'],
    summary: 'Remove a specific list of contacts from a campaign',
    operationId: 'deleteCampaignContactsByList',
    requestBody: requestBody({ campaignId: { type: 'integer' }, contactIds: { type: 'array', items: { type: 'string' } } }),
  }));
  addOp(paths, '/api/command/crm/tags', 'post', op({
    tags: ['CRM'],
    summary: 'Create or update a CRM tag (upsert by name)',
    operationId: 'upsertCrmTag',
    requestBody: requestBody({ zaloId: { type: 'string' }, tag: { type: 'object', properties: { name: { type: 'string' }, color: { type: 'string' } } } }),
  }));
  addOp(paths, '/api/command/crm/tags/{id}', 'delete', op({
    tags: ['CRM'],
    summary: 'Delete a CRM tag',
    operationId: 'deleteCrmTag',
    parameters: [pp('id', 'integer')],
  }));
  addOp(paths, '/api/command/crm/tags/assign', 'post', op({
    tags: ['CRM'],
    summary: 'Assign a CRM tag to a contact',
    operationId: 'assignCrmTag',
    requestBody: requestBody({ zaloId: { type: 'string' }, tagId: { type: 'integer' }, contactId: { type: 'string' } }),
  }));
  addOp(paths, '/api/command/crm/tags/{id}/contacts/{contactId}', 'delete', op({
    tags: ['CRM'],
    summary: 'Remove a CRM tag from a contact',
    operationId: 'removeCrmTagFromContact',
    parameters: [pp('id', 'integer'), pp('contactId')],
  }));

  // ═══════════════════════════════════════════════════════════════
  // LABELS (local labels — query + command)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/labels', 'get', op({
    tags: ['Labels'],
    summary: 'Get local labels for an account (cached, short TTL)',
    operationId: 'getLabels',
    parameters: [qp('zaloId')],
  }));
  addOp(paths, '/api/query/label-threads', 'get', op({
    tags: ['Labels'],
    summary: 'Get all thread→label assignments for an account (cached, short TTL)',
    operationId: 'getLabelThreads',
    parameters: [qp('zaloId', 'string', true)],
  }));
  addOp(paths, '/api/query/label-threads/thread', 'get', op({
    tags: ['Labels'],
    summary: 'Get labels assigned to a specific thread',
    operationId: 'getThreadLabelsHandler',
    parameters: [qp('zaloId', 'string', true), qp('threadId', 'string', true)],
  }));

  addOp(paths, '/api/command/labels', 'post', op({
    tags: ['Labels'],
    summary: 'Create or update a local label',
    operationId: 'upsertLabel',
    requestBody: requestBody({ label: { type: 'object' } }),
  }));
  addOp(paths, '/api/command/labels/{id}', 'delete', op({
    tags: ['Labels'],
    summary: 'Delete a local label',
    operationId: 'deleteLabel',
    parameters: [pp('id', 'integer')],
  }));
  addOp(paths, '/api/command/labels/clone', 'post', op({
    tags: ['Labels'],
    summary: 'Clone all local labels from one account to another',
    operationId: 'cloneLabels',
    requestBody: requestBody({ sourceZaloId: { type: 'string' }, targetZaloId: { type: 'string' } }),
  }));
  addOp(paths, '/api/command/labels/{id}/active', 'patch', op({
    tags: ['Labels'],
    summary: 'Enable/disable a local label',
    operationId: 'setLabelActive',
    parameters: [pp('id', 'integer')],
    requestBody: requestBody({ isActive: { type: 'boolean' } }),
  }));
  addOp(paths, '/api/command/labels/{id}/order', 'patch', op({
    tags: ['Labels'],
    summary: 'Reorder a local label',
    operationId: 'setLabelOrder',
    parameters: [pp('id', 'integer')],
    requestBody: requestBody({ order: { type: 'integer' } }),
  }));
  addOp(paths, '/api/command/label-threads', 'post', op({
    tags: ['Labels'],
    summary: 'Assign a local label to a thread',
    operationId: 'assignLabelToThread',
    requestBody: requestBody({ zaloId: { type: 'string' }, labelId: { type: 'integer' }, threadId: { type: 'string' } }),
  }));
  addOp(paths, '/api/command/label-threads', 'delete', op({
    tags: ['Labels'],
    summary: 'Remove a local label from a thread',
    operationId: 'removeLabelFromThread',
    requestBody: requestBody({ zaloId: { type: 'string' }, labelId: { type: 'integer' }, threadId: { type: 'string' } }),
  }));

  // ═══════════════════════════════════════════════════════════════
  // QUICK MESSAGES (query + command)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/quick-messages', 'get', op({
    tags: ['QuickMessages'],
    summary: 'Get local quick messages for an account',
    operationId: 'getQuickMessages',
    parameters: [qp('zaloId', 'string', true)],
  }));
  addOp(paths, '/api/query/quick-messages/all', 'get', op({
    tags: ['QuickMessages'],
    summary: 'Get all local quick messages across all accounts',
    operationId: 'getAllQuickMessagesHandler',
  }));

  addOp(paths, '/api/command/quick-messages', 'post', op({
    tags: ['QuickMessages'],
    summary: 'Create or update a local quick message',
    operationId: 'upsertQuickMessage',
    requestBody: requestBody({ zaloId: { type: 'string' }, item: { type: 'object' } }),
  }));
  addOp(paths, '/api/command/quick-messages/{id}', 'delete', op({
    tags: ['QuickMessages'],
    summary: 'Delete a local quick message',
    operationId: 'deleteQuickMessage',
    parameters: [pp('id', 'integer'), qp('zaloId')],
  }));
  addOp(paths, '/api/command/quick-messages/bulk-replace', 'post', op({
    tags: ['QuickMessages'],
    summary: 'Bulk-replace all local quick messages for an account',
    operationId: 'bulkReplaceQuickMessages',
    requestBody: requestBody({ zaloId: { type: 'string' }, items: { type: 'array', items: { type: 'object' } } }),
  }));
  addOp(paths, '/api/command/quick-messages/clone', 'post', op({
    tags: ['QuickMessages'],
    summary: 'Clone quick messages from one account to another',
    operationId: 'cloneQuickMessages',
    requestBody: requestBody({ sourceZaloId: { type: 'string' }, targetZaloId: { type: 'string' } }),
  }));
  addOp(paths, '/api/command/quick-messages/{id}/active', 'patch', op({
    tags: ['QuickMessages'],
    summary: 'Enable/disable a local quick message',
    operationId: 'setQuickMessageActive',
    parameters: [pp('id', 'integer')],
    requestBody: requestBody({ isActive: { type: 'boolean' } }),
  }));
  addOp(paths, '/api/command/quick-messages/{id}/order', 'patch', op({
    tags: ['QuickMessages'],
    summary: 'Reorder a local quick message',
    operationId: 'setQuickMessageOrder',
    parameters: [pp('id', 'integer')],
    requestBody: requestBody({ order: { type: 'integer' } }),
  }));

  // ═══════════════════════════════════════════════════════════════
  // DRAFTS (query + command)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/drafts', 'get', op({
    tags: ['Drafts'],
    summary: 'Get all drafts for an account',
    operationId: 'getDrafts',
    parameters: [qp('zaloId', 'string', true)],
  }));
  addOp(paths, '/api/query/drafts/single', 'get', op({
    tags: ['Drafts'],
    summary: 'Get the draft for a specific thread',
    operationId: 'getSingleDraftHandler',
    parameters: [qp('zaloId', 'string', true), qp('threadId', 'string', true)],
  }));

  addOp(paths, '/api/command/drafts/{threadId}', 'put', op({
    tags: ['Drafts'],
    summary: 'Create or update the draft for a thread',
    operationId: 'upsertDraft',
    parameters: [pp('threadId'), qp('zaloId')],
    requestBody: requestBody({ content: { type: 'string' } }),
  }));
  addOp(paths, '/api/command/drafts/{threadId}', 'delete', op({
    tags: ['Drafts'],
    summary: 'Delete the draft for a thread',
    operationId: 'deleteDraft',
    parameters: [pp('threadId'), qp('zaloId')],
  }));
  addOp(paths, '/api/command/drafts/cleanup', 'post', op({
    tags: ['Drafts'],
    summary: 'Delete drafts older than N days',
    operationId: 'cleanupOldDrafts',
    requestBody: requestBody({ days: { type: 'integer' } }),
  }));

  // ═══════════════════════════════════════════════════════════════
  // LINKS
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/links', 'get', op({
    tags: ['Links'],
    summary: 'Get shared links in a thread',
    operationId: 'getLinks',
    parameters: [qp('zaloId', 'string', true), qp('threadId', 'string', true), qp('limit', 'integer'), qp('offset', 'integer')],
  }));
  addOp(paths, '/api/command/links', 'post', op({
    tags: ['Links'],
    summary: 'Save a shared link detected in a message',
    operationId: 'saveLink',
    requestBody: requestBody({
      zaloId: { type: 'string' }, threadId: { type: 'string' }, msgId: { type: 'string' },
      url: { type: 'string' }, title: { type: 'string' }, domain: { type: 'string' },
      thumbUrl: { type: 'string' }, timestamp: { type: 'integer' },
    }),
  }));

  // ═══════════════════════════════════════════════════════════════
  // SETTINGS (query + command)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/settings/{key}', 'get', op({
    tags: ['Settings'],
    summary: 'Get a single app setting by key',
    operationId: 'getSetting',
    parameters: [pp('key')],
  }));
  addOp(paths, '/api/query/settings', 'get', op({
    tags: ['Settings'],
    summary: 'Get all app settings (key/value list)',
    operationId: 'getAllSettings',
  }));
  addOp(paths, '/api/query/settings/notif', 'get', op({
    tags: ['Settings'],
    summary: 'Get notification settings for an account',
    operationId: 'getNotifSettings',
    parameters: [qp('zaloId')],
  }));
  addOp(paths, '/api/command/settings/{key}', 'put', op({
    tags: ['Settings'],
    summary: 'Set a single app setting by key',
    operationId: 'setSetting',
    parameters: [pp('key')],
    requestBody: requestBody({ value: { type: 'string' } }),
  }));

  // ═══════════════════════════════════════════════════════════════
  // PINNED CONVERSATIONS / MESSAGES
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/pinned-conversations', 'get', op({
    tags: ['Conversations'],
    summary: 'Get pinned conversation thread ids for an account (cached, short TTL)',
    operationId: 'getPinnedConversations',
    parameters: [qp('zaloId', 'string', true)],
  }));
  addOp(paths, '/api/command/pinned-conversations', 'post', op({
    tags: ['Conversations'],
    summary: 'Pin or unpin a conversation',
    operationId: 'setPinnedConversation',
    requestBody: requestBody({ zaloId: { type: 'string' }, threadId: { type: 'string' }, isPinned: { type: 'boolean' } }),
  }));
  addOp(paths, '/api/command/pinned-messages', 'post', op({
    tags: ['Messages'],
    summary: 'Pin a message in a thread',
    operationId: 'pinMessage',
    requestBody: requestBody({ zaloId: { type: 'string' }, threadId: { type: 'string' }, pin: { type: 'object' } }),
  }));
  addOp(paths, '/api/command/pinned-messages/{msgId}', 'delete', op({
    tags: ['Messages'],
    summary: 'Unpin a message from a thread',
    operationId: 'unpinMessage',
    parameters: [pp('msgId'), qp('zaloId')],
    requestBody: requestBody({ threadId: { type: 'string' } }, false),
  }));
  addOp(paths, '/api/command/pinned-messages/{msgId}', 'put', op({
    tags: ['Messages'],
    summary: "Bring a pinned message to the top of the pin list — msgId path segment is literally 'bring-to-top', the real message id is passed in the body",
    operationId: 'bringPinnedMessageToTop',
    parameters: [pp('msgId', 'string', "Literal sentinel value 'bring-to-top'"), qp('zaloId')],
    requestBody: requestBody({ threadId: { type: 'string' }, msgId: { type: 'string' } }),
  }));

  // ═══════════════════════════════════════════════════════════════
  // STICKERS (query + command)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/sticker-packs', 'get', op({
    tags: ['Stickers'],
    summary: 'Get all sticker packs',
    operationId: 'getStickerPacksHandler',
  }));
  addOp(paths, '/api/query/sticker-packs/summaries', 'get', op({
    tags: ['Stickers'],
    summary: 'Get cached sticker pack summaries',
    operationId: 'getCachedPackSummariesHandler',
  }));
  addOp(paths, '/api/query/stickers/recent', 'get', op({
    tags: ['Stickers'],
    summary: 'Get recently used stickers',
    operationId: 'getRecentStickersHandler',
    parameters: [qp('limit', 'integer')],
  }));
  addOp(paths, '/api/query/stickers/by-ids', 'get', op({
    tags: ['Stickers'],
    summary: 'Get stickers by a list of ids',
    operationId: 'getStickersByIdsHandler',
    parameters: [qp('stickerIds', 'array'), qp('ids', 'array')],
  }));
  addOp(paths, '/api/query/stickers/by-ids', 'post', op({
    tags: ['Stickers'],
    summary: 'Get stickers by a list of ids (POST variant — same handler as GET, used when the id list is large)',
    operationId: 'getStickersByIdsHandlerPost',
    requestBody: requestBody({ stickerIds: { type: 'array', items: { type: 'integer' } }, ids: { type: 'array', items: { type: 'integer' } } }, false),
  }));
  addOp(paths, '/api/query/stickers/by-id', 'get', op({
    tags: ['Stickers'],
    summary: 'Get a single sticker by id',
    operationId: 'getStickerByIdHandler',
    parameters: [qp('stickerId', 'integer', true)],
  }));
  addOp(paths, '/api/query/stickers/keyword', 'get', op({
    tags: ['Stickers'],
    summary: 'Get stickers mapped to a keyword',
    operationId: 'getKeywordStickersHandler',
    parameters: [qp('keyword', 'string', true)],
  }));

  addOp(paths, '/api/command/stickers/save', 'post', op({
    tags: ['Stickers'],
    summary: 'Bulk-save stickers into the local cache',
    operationId: 'saveStickers',
    requestBody: requestBody({ stickers: { type: 'array', items: { type: 'object' } } }),
  }));
  addOp(paths, '/api/command/sticker-packs/save', 'post', op({
    tags: ['Stickers'],
    summary: 'Bulk-save sticker packs into the local cache',
    operationId: 'saveStickerPacks',
    requestBody: requestBody({ packs: { type: 'array', items: { type: 'object' } } }),
  }));
  addOp(paths, '/api/command/stickers/recent', 'post', op({
    tags: ['Stickers'],
    summary: 'Record a sticker as recently used',
    operationId: 'addRecentSticker',
    requestBody: requestBody({ stickerId: { type: 'integer' } }),
  }));
  addOp(paths, '/api/command/stickers/keyword', 'post', op({
    tags: ['Stickers'],
    summary: 'Save keyword→sticker mapping',
    operationId: 'saveKeywordStickers',
    requestBody: requestBody({ keyword: { type: 'string' }, stickerIds: { type: 'array', items: { type: 'integer' } } }),
  }));

  // ═══════════════════════════════════════════════════════════════
  // BANK CARDS
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/bank-cards', 'get', op({
    tags: ['BankCards'],
    summary: 'Get saved bank cards for an account',
    operationId: 'getBankCardsHandler',
    parameters: [qp('zaloId', 'string', true)],
  }));
  addOp(paths, '/api/command/bank-cards', 'post', op({
    tags: ['BankCards'],
    summary: 'Create or update a bank card',
    operationId: 'upsertBankCard',
    requestBody: requestBody({ zaloId: { type: 'string' }, card: { type: 'object' } }),
  }));
  addOp(paths, '/api/command/bank-cards/{id}', 'delete', op({
    tags: ['BankCards'],
    summary: 'Delete a bank card',
    operationId: 'deleteBankCard',
    parameters: [pp('id', 'integer'), qp('zaloId')],
  }));

  // ═══════════════════════════════════════════════════════════════
  // PROXIES
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/proxies', 'get', op({
    tags: ['Proxies'],
    summary: 'Get all configured proxies',
    operationId: 'getProxies',
  }));
  addOp(paths, '/api/query/proxies/{id}', 'get', op({
    tags: ['Proxies'],
    summary: 'Get a proxy by id',
    operationId: 'getProxyById',
    parameters: [pp('id', 'integer')],
  }));
  addOp(paths, '/api/command/proxies', 'post', op({
    tags: ['Proxies'],
    summary: 'Create or update a proxy',
    operationId: 'saveProxy',
    requestBody: requestBody({ proxy: { type: 'object' } }),
  }));
  addOp(paths, '/api/command/proxies/{id}', 'delete', op({
    tags: ['Proxies'],
    summary: 'Delete a proxy',
    operationId: 'deleteProxy',
    parameters: [pp('id', 'integer')],
  }));

  // ═══════════════════════════════════════════════════════════════
  // ACCOUNTS (proxy assignment, phone) / FRIENDS / GROUPS commands
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/command/accounts/proxy', 'post', op({
    tags: ['Proxies'],
    summary: 'Assign a proxy to an account',
    operationId: 'assignProxyToAccount',
    requestBody: requestBody({ zaloId: { type: 'string' }, proxyId: { type: 'integer' } }),
  }));
  addOp(paths, '/api/command/accounts/phone', 'post', op({
    tags: ['Conversations'],
    summary: "Update an account's phone number",
    operationId: 'updateAccountPhone',
    requestBody: requestBody({ zaloId: { type: 'string' }, phone: { type: 'string' } }),
  }));
  addOp(paths, '/api/command/conversations/{contactId}/flags', 'patch', op({
    tags: ['Conversations'],
    summary: 'Set flags on a contact (e.g. spam/blocked markers)',
    operationId: 'setContactFlags',
    parameters: [pp('contactId'), qp('zaloId')],
    requestBody: requestBody({ flags: { type: 'object' } }),
  }));
  addOp(paths, '/api/command/conversations/{contactId}/alias', 'patch', op({
    tags: ['Conversations'],
    summary: 'Set a local alias for a contact',
    operationId: 'setContactAlias',
    parameters: [pp('contactId'), qp('zaloId')],
    requestBody: requestBody({ alias: { type: 'string' } }),
  }));
  addOp(paths, '/api/command/conversations/update-profile', 'post', op({
    tags: ['Conversations'],
    summary: "Update a contact's profile fields (display name, avatar, phone, gender, birthday...)",
    operationId: 'updateContactProfile',
    requestBody: requestBody({
      zaloId: { type: 'string' }, contactId: { type: 'string' }, displayName: { type: 'string' },
      avatarUrl: { type: 'string' }, phone: { type: 'string' }, contactType: { type: 'string' },
      gender: { type: 'integer', nullable: true }, birthday: { type: 'string', nullable: true },
      manualDetails: { type: 'boolean' },
    }),
  }));
  addOp(paths, '/api/command/conversations/{contactId}', 'delete', op({
    tags: ['Conversations'],
    summary: 'Delete a conversation',
    operationId: 'deleteConversation',
    parameters: [pp('contactId'), qp('zaloId')],
  }));

  addOp(paths, '/api/command/friends/batch', 'post', op({
    tags: ['Friends'],
    summary: 'Bulk-save a batch of friends for an account',
    operationId: 'saveFriendsBatch',
    requestBody: requestBody({ zaloId: { type: 'string' }, friends: { type: 'array', items: { type: 'object' } } }),
  }));
  addOp(paths, '/api/command/friends', 'post', op({
    tags: ['Friends'],
    summary: 'Add a single friend',
    operationId: 'addFriend',
    requestBody: requestBody({ zaloId: { type: 'string' }, friend: { type: 'object' } }),
  }));
  addOp(paths, '/api/command/friends/{userId}', 'delete', op({
    tags: ['Friends'],
    summary: 'Remove a friend',
    operationId: 'removeFriend',
    parameters: [pp('userId'), qp('zaloId')],
  }));
  addOp(paths, '/api/command/friend-requests', 'post', op({
    tags: ['FriendRequests'],
    summary: 'Create or update a friend request (sent or received)',
    operationId: 'upsertFriendRequest',
    requestBody: requestBody({ zaloId: { type: 'string' }, request: { type: 'object' }, direction: { type: 'string', description: "'sent' | 'received'" } }),
  }));
  addOp(paths, '/api/command/friend-requests/{userId}', 'delete', op({
    tags: ['FriendRequests'],
    summary: 'Remove a friend request',
    operationId: 'removeFriendRequest',
    parameters: [pp('userId'), qp('zaloId'), qp('direction', 'string', false, "'sent' | 'received'")],
  }));

  addOp(paths, '/api/command/groups/members/upsert', 'post', op({
    tags: ['Groups'],
    summary: 'Add or update a group member',
    operationId: 'upsertGroupMember',
    requestBody: requestBody({ zaloId: { type: 'string' }, groupId: { type: 'string' }, member: { type: 'object' } }),
  }));
  addOp(paths, '/api/command/groups/members/{memberId}', 'delete', op({
    tags: ['Groups'],
    summary: 'Remove a member from a group',
    operationId: 'removeGroupMember',
    parameters: [pp('memberId'), qp('zaloId')],
    requestBody: requestBody({ groupId: { type: 'string' } }, false),
  }));

  // ═══════════════════════════════════════════════════════════════
  // MESSAGES — write commands
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/command/messages/mark-read', 'post', op({
    tags: ['Messages'],
    summary: 'Mark all messages in a conversation as read',
    operationId: 'markMessagesRead',
    requestBody: requestBody({ zaloId: { type: 'string' }, contactId: { type: 'string' } }),
  }));
  addOp(paths, '/api/command/messages/mark-recalled', 'post', op({
    tags: ['Messages'],
    summary: 'Mark a message as recalled/undone',
    operationId: 'markMessageRecalled',
    requestBody: requestBody({ zaloId: { type: 'string' }, msgId: { type: 'string' } }),
  }));
  addOp(paths, '/api/command/messages/delete', 'post', op({
    tags: ['Messages'],
    summary: 'Delete one or more messages',
    operationId: 'deleteMessages',
    requestBody: requestBody({ zaloId: { type: 'string' }, msgIds: { type: 'array', items: { type: 'string' } } }),
  }));
  addOp(paths, '/api/command/messages/reaction', 'post', op({
    tags: ['Messages'],
    summary: 'Sync a message reaction from employee to Boss DB (Boss DB is typically already updated by the relay webhook)',
    operationId: 'syncMessageReaction',
    requestBody: requestBody({ zaloId: { type: 'string' }, msgId: { type: 'string' } }, false),
  }));
  addOp(paths, '/api/command/messages/local-paths', 'post', op({
    tags: ['Messages'],
    summary: 'Update the locally-cached file paths for a message\'s attachments',
    operationId: 'updateMessageLocalPaths',
    requestBody: requestBody({ zaloId: { type: 'string' }, msgId: { type: 'string' }, threadId: { type: 'string' }, localPaths: { type: 'object' } }),
  }));

  // ═══════════════════════════════════════════════════════════════
  // ERP TASKS (query + command)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/erp/projects', 'get', op({
    tags: ['ERP-Tasks'],
    summary: 'List ERP projects',
    operationId: 'getErpProjects',
    parameters: [qp('archived', 'boolean')],
  }));
  addOp(paths, '/api/query/erp/tasks', 'get', op({
    tags: ['ERP-Tasks'],
    summary: 'List ERP tasks with filters (project, assignee, priority, status, search, pagination) — non-privileged employees only see tasks they are involved in',
    operationId: 'getErpTasks',
    parameters: [
      qp('projectId'), qp('assigneeId'), qp('priority'), qp('status'), qp('search'),
      qp('archived', 'boolean'), qp('parentTaskId'), qp('limit', 'integer'), qp('offset', 'integer'),
      qp('dueRange', 'object', false, 'JSON-encoded { from, to } range'),
    ],
  }));
  addOp(paths, '/api/query/erp/tasks/inbox', 'get', op({
    tags: ['ERP-Tasks'],
    summary: "Get the employee's task inbox (assigned/watching/reported), filtered by time window",
    operationId: 'getErpMyInbox',
    parameters: [qp('filter', 'string', false, "e.g. 'week' (default)")],
  }));
  addOp(paths, '/api/query/erp/tasks/{id}', 'get', op({
    tags: ['ERP-Tasks'],
    summary: 'Get full task detail (permission-checked: reporter/assignee/watcher or privileged role)',
    operationId: 'getErpTaskDetail',
    parameters: [pp('id')],
  }));

  addOp(paths, '/api/command/erp/tasks', 'post', op({
    tags: ['ERP-Tasks'],
    summary: 'Create an ERP task',
    operationId: 'createErpTaskCommand',
    requestBody: requestBody({ input: { type: 'object', description: 'Task fields, e.g. title, description, projectId, priority' } }),
  }));
  addOp(paths, '/api/command/erp/tasks/assign', 'post', op({
    tags: ['ERP-Tasks'],
    summary: 'Assign a task to one or more employees',
    operationId: 'assignErpTaskCommand',
    requestBody: requestBody({ id: { type: 'string' }, employeeIds: { type: 'array', items: { type: 'string' } } }),
  }));
  addOp(paths, '/api/command/erp/tasks/watcher', 'post', op({
    tags: ['ERP-Tasks'],
    summary: 'Add or remove a watcher on a task',
    operationId: 'erpTaskWatcher',
    requestBody: requestBody({ taskId: { type: 'string' }, employeeId: { type: 'string' }, action: { type: 'string', description: "'add' (default) | 'remove'" } }),
  }));
  addOp(paths, '/api/command/erp/tasks/comment', 'post', op({
    tags: ['ERP-Tasks'],
    summary: 'Add a comment to a task',
    operationId: 'addErpTaskCommentCommand',
    requestBody: requestBody({ taskId: { type: 'string' }, content: { type: 'string' }, mentions: { type: 'array', items: { type: 'string' } } }),
  }));
  addOp(paths, '/api/command/erp/tasks/checklist', 'post', op({
    tags: ['ERP-Tasks'],
    summary: 'Add a checklist item to a task',
    operationId: 'addErpTaskChecklistCommand',
    requestBody: requestBody({ taskId: { type: 'string' }, content: { type: 'string' } }),
  }));
  addOp(paths, '/api/command/erp/tasks/checklist/{id}/toggle', 'patch', op({
    tags: ['ERP-Tasks'],
    summary: 'Toggle a task checklist item done/not-done',
    operationId: 'toggleErpTaskChecklistCommand',
    parameters: [pp('id', 'integer')],
    requestBody: requestBody({ done: { type: 'boolean' } }),
  }));
  addOp(paths, '/api/command/erp/tasks/{id}/status', 'patch', op({
    tags: ['ERP-Tasks'],
    summary: "Update a task's status",
    operationId: 'updateErpTaskStatusCommand',
    parameters: [pp('id')],
    requestBody: requestBody({ status: { type: 'string' } }),
  }));
  addOp(paths, '/api/command/erp/tasks/{id}', 'patch', op({
    tags: ['ERP-Tasks'],
    summary: 'Update a task (partial patch of task fields)',
    operationId: 'updateErpTaskCommand',
    parameters: [pp('id')],
    requestBody: requestBody({ patch: { type: 'object' } }),
  }));
  addOp(paths, '/api/command/erp/tasks/{id}', 'delete', op({
    tags: ['ERP-Tasks'],
    summary: 'Delete a task',
    operationId: 'deleteErpTaskCommand',
    parameters: [pp('id')],
  }));
  addOp(paths, '/api/command/erp/projects', 'post', op({
    tags: ['ERP-Tasks'],
    summary: 'Create an ERP project',
    operationId: 'createErpProjectCommand',
    requestBody: requestBody({ name: { type: 'string' }, description: { type: 'string' }, color: { type: 'string' }, department_id: { type: 'string' } }),
  }));

  // ═══════════════════════════════════════════════════════════════
  // ERP HRM — departments / positions / profiles
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/erp/departments', 'get', op({
    tags: ['ERP-HRM'],
    summary: 'List ERP departments',
    operationId: 'getErpDepartments',
  }));
  addOp(paths, '/api/query/erp/positions', 'get', op({
    tags: ['ERP-HRM'],
    summary: 'List ERP positions',
    operationId: 'getErpPositions',
  }));
  addOp(paths, '/api/query/erp/profiles', 'get', op({
    tags: ['ERP-HRM'],
    summary: 'List ERP employee profiles, optionally filtered by department',
    operationId: 'getErpProfiles',
    parameters: [qp('departmentId')],
  }));
  addOp(paths, '/api/query/erp/profiles/{employeeId}', 'get', op({
    tags: ['ERP-HRM'],
    summary: 'Get a single ERP employee profile',
    operationId: 'getErpProfile',
    parameters: [pp('employeeId')],
  }));

  // ═══════════════════════════════════════════════════════════════
  // ERP CALENDAR (query + command)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/erp/calendar/events', 'get', op({
    tags: ['ERP-Calendar'],
    summary: 'List ERP calendar events overlapping a time range for an organizer',
    operationId: 'getErpCalendarEvents',
    parameters: [qp('from', 'integer'), qp('to', 'integer'), qp('organizerId')],
  }));
  addOp(paths, '/api/command/erp/calendar', 'post', op({
    tags: ['ERP-Calendar'],
    summary: 'Create an ERP calendar event',
    operationId: 'createErpCalendarEvent',
    requestBody: requestBody({ input: { type: 'object', description: 'Event fields, e.g. title, startAt, endAt' } }),
  }));
  addOp(paths, '/api/command/erp/calendar/{id}', 'patch', op({
    tags: ['ERP-Calendar'],
    summary: 'Update an ERP calendar event (partial patch)',
    operationId: 'updateErpCalendarEvent',
    parameters: [pp('id')],
    requestBody: requestBody({ patch: { type: 'object' } }),
  }));
  addOp(paths, '/api/command/erp/calendar/{id}', 'delete', op({
    tags: ['ERP-Calendar'],
    summary: 'Delete an ERP calendar event',
    operationId: 'deleteErpCalendarEvent',
    parameters: [pp('id')],
  }));

  // ═══════════════════════════════════════════════════════════════
  // ANALYTICS
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/analytics/dashboard', 'get', op({
    tags: ['Analytics'],
    summary: 'Get dashboard overview metrics for an account',
    operationId: 'getDashboardOverview',
    parameters: [qp('zaloId', 'string', true)],
  }));
  addOp(paths, '/api/query/analytics/message-volume', 'get', op({
    tags: ['Analytics'],
    summary: 'Get message volume over time, bucketed by granularity',
    operationId: 'getMessageVolume',
    parameters: [qp('zaloId', 'string', true), qp('sinceTs', 'integer'), qp('untilTs', 'integer'), qp('granularity', 'string', false, "e.g. 'day' (default)"), qp('threadType', 'integer')],
  }));
  addOp(paths, '/api/query/analytics/peak-hours', 'get', op({
    tags: ['Analytics'],
    summary: 'Get a peak-hours heatmap of message activity',
    operationId: 'getPeakHours',
    parameters: [qp('zaloId', 'string', true), qp('sinceTs', 'integer'), qp('untilTs', 'integer'), qp('threadType', 'integer')],
  }));
  addOp(paths, '/api/query/analytics/segmentation', 'get', op({
    tags: ['Analytics'],
    summary: 'Get contact segmentation breakdown',
    operationId: 'getContactSegmentation',
    parameters: [qp('zaloId', 'string', true)],
  }));
  addOp(paths, '/api/query/analytics/campaign-comparison', 'get', op({
    tags: ['Analytics'],
    summary: 'Compare CRM campaign performance',
    operationId: 'getCampaignComparison',
    parameters: [qp('zaloId', 'string', true)],
  }));
  addOp(paths, '/api/query/analytics/friend-requests', 'get', op({
    tags: ['Analytics'],
    summary: 'Get friend request analytics over a time range',
    operationId: 'getFriendRequestAnalytics',
    parameters: [qp('zaloId', 'string', true), qp('sinceTs', 'integer'), qp('untilTs', 'integer')],
  }));
  addOp(paths, '/api/query/analytics/contact-growth', 'get', op({
    tags: ['Analytics'],
    summary: 'Get contact growth over a time range',
    operationId: 'getContactGrowth',
    parameters: [qp('zaloId', 'string', true), qp('sinceTs', 'integer'), qp('untilTs', 'integer')],
  }));
  addOp(paths, '/api/query/analytics/workflows', 'get', op({
    tags: ['Analytics'],
    summary: 'Get workflow execution analytics over a time range',
    operationId: 'getWorkflowAnalytics',
    parameters: [qp('zaloId', 'string', true), qp('sinceTs', 'integer'), qp('untilTs', 'integer')],
  }));
  addOp(paths, '/api/query/analytics/ai', 'get', op({
    tags: ['Analytics'],
    summary: 'Get AI assistant usage analytics over a time range (not scoped to a single account)',
    operationId: 'getAIAnalytics',
    parameters: [qp('sinceTs', 'integer'), qp('untilTs', 'integer')],
  }));
  addOp(paths, '/api/query/analytics/response-time', 'get', op({
    tags: ['Analytics'],
    summary: 'Get response-time statistics over a time range',
    operationId: 'getResponseTime',
    parameters: [qp('zaloId', 'string', true), qp('sinceTs', 'integer'), qp('untilTs', 'integer'), qp('threadType', 'integer')],
  }));
  addOp(paths, '/api/query/analytics/label-usage', 'get', op({
    tags: ['Analytics'],
    summary: 'Get local-label usage analytics over a time range',
    operationId: 'getLabelUsage',
    parameters: [qp('zaloId', 'string', true), qp('sinceTs', 'integer'), qp('untilTs', 'integer')],
  }));

  // ═══════════════════════════════════════════════════════════════
  // WORKFLOW (query + command)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/workflows', 'get', op({
    tags: ['Workflow'],
    summary: 'List all workflows',
    operationId: 'getWorkflows',
  }));
  addOp(paths, '/api/query/workflows/run-logs', 'get', op({
    tags: ['Workflow'],
    summary: 'Get the most recent workflow run logs across all workflows',
    operationId: 'getRecentRunLogs',
    parameters: [qp('limit', 'integer')],
  }));
  addOp(paths, '/api/query/workflows/{id}/run-logs', 'get', op({
    tags: ['Workflow'],
    summary: 'Get run logs for a specific workflow',
    operationId: 'getWorkflowRunLogs',
    parameters: [pp('id'), qp('limit', 'integer')],
  }));
  addOp(paths, '/api/query/workflows/{id}', 'get', op({
    tags: ['Workflow'],
    summary: 'Get a workflow by id',
    operationId: 'getWorkflowById',
    parameters: [pp('id')],
  }));

  addOp(paths, '/api/command/workflows', 'post', op({
    tags: ['Workflow'],
    summary: 'Create or update a workflow (node/edge graph)',
    operationId: 'saveWorkflow',
    requestBody: requestBody({ workflow: { type: 'object' } }),
  }));
  addOp(paths, '/api/command/workflows/{id}/toggle', 'patch', op({
    tags: ['Workflow'],
    summary: 'Enable/disable a workflow',
    operationId: 'toggleWorkflow',
    parameters: [pp('id')],
    requestBody: requestBody({ enabled: { type: 'boolean' } }),
  }));
  addOp(paths, '/api/command/workflows/{id}', 'delete', op({
    tags: ['Workflow'],
    summary: 'Delete a workflow',
    operationId: 'deleteWorkflow',
    parameters: [pp('id')],
  }));

  // ═══════════════════════════════════════════════════════════════
  // INTEGRATIONS (query + command)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/integrations', 'get', op({
    tags: ['Integrations'],
    summary: 'List configured integrations (KiotViet/Haravan/Sapo/Nhanh/Pancake/Casso/SePay/GHN/GHTK...)',
    operationId: 'getIntegrations',
  }));
  addOp(paths, '/api/command/integrations', 'post', op({
    tags: ['Integrations'],
    summary: 'Create or update an integration configuration',
    operationId: 'saveIntegration',
    requestBody: requestBody({ integration: { type: 'object' } }),
  }));
  addOp(paths, '/api/command/integrations/{id}/toggle', 'patch', op({
    tags: ['Integrations'],
    summary: 'Enable/disable an integration',
    operationId: 'toggleIntegration',
    parameters: [pp('id')],
    requestBody: requestBody({ enabled: { type: 'boolean' } }),
  }));
  addOp(paths, '/api/command/integrations/{id}', 'delete', op({
    tags: ['Integrations'],
    summary: 'Delete an integration configuration',
    operationId: 'deleteIntegration',
    parameters: [pp('id')],
  }));

  // ═══════════════════════════════════════════════════════════════
  // AI ASSISTANTS (query + command + chat)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/query/ai/assistants', 'get', op({
    tags: ['AI'],
    summary: 'List AI assistants (API keys masked)',
    operationId: 'getAiAssistants',
  }));
  addOp(paths, '/api/query/ai/assistants/{id}', 'get', op({
    tags: ['AI'],
    summary: 'Get an AI assistant by id (API key masked)',
    operationId: 'getAiAssistant',
    parameters: [pp('id')],
  }));
  addOp(paths, '/api/query/ai/assistants/{id}/files', 'get', op({
    tags: ['AI'],
    summary: 'List files attached to an AI assistant',
    operationId: 'getAiAssistantFiles',
    parameters: [pp('id')],
  }));
  addOp(paths, '/api/query/ai/usage-stats', 'get', op({
    tags: ['AI'],
    summary: 'Get AI usage statistics',
    operationId: 'getAiUsageStats',
    parameters: [qp('assistantId'), qp('days', 'integer')],
  }));
  addOp(paths, '/api/query/ai/usage-logs', 'get', op({
    tags: ['AI'],
    summary: 'Get AI usage logs',
    operationId: 'getAiUsageLogs',
    parameters: [qp('assistantId'), qp('limit', 'integer')],
  }));
  addOp(paths, '/api/query/ai/default', 'get', op({
    tags: ['AI'],
    summary: 'Get the default AI assistant (API key masked)',
    operationId: 'getAiDefaultAssistant',
  }));
  addOp(paths, '/api/query/ai/account-assistant', 'get', op({
    tags: ['AI'],
    summary: 'Get the AI assistant configured for an account/role (API key masked)',
    operationId: 'getAiAccountAssistant',
    parameters: [qp('zaloId'), qp('role', 'string', false, "e.g. 'suggestion' (default)")],
  }));
  addOp(paths, '/api/query/ai/account-assistants', 'get', op({
    tags: ['AI'],
    summary: 'Get all AI assistant role assignments for an account',
    operationId: 'getAiAccountAssistants',
    parameters: [qp('zaloId')],
  }));

  addOp(paths, '/api/command/ai/chat', 'post', op({
    tags: ['AI'],
    summary: 'Send a chat message to an AI assistant and get a completion (proxies the LLM call through Boss)',
    operationId: 'aiChat',
    requestBody: requestBody({
      assistantId: { type: 'string' },
      messages: { type: 'array', items: { type: 'object' } },
      structured: { type: 'boolean' },
      maxTokens: { type: 'integer' },
    }),
  }));
  addOp(paths, '/api/command/ai/suggest', 'post', op({
    tags: ['AI'],
    summary: 'Get AI-generated reply suggestions for a chat history (proxies the LLM call through Boss)',
    operationId: 'aiSuggest',
    requestBody: requestBody({
      assistantId: { type: 'string' },
      chatHistory: { type: 'array', items: { type: 'object' } },
    }),
  }));
  addOp(paths, '/api/command/ai/assistants', 'post', op({
    tags: ['AI'],
    summary: 'Create or update an AI assistant configuration',
    operationId: 'saveAiAssistant',
    requestBody: requestBody({ assistant: { type: 'object' } }),
  }));
  addOp(paths, '/api/command/ai/assistants/{id}', 'delete', op({
    tags: ['AI'],
    summary: 'Delete an AI assistant',
    operationId: 'deleteAiAssistant',
    parameters: [pp('id')],
  }));

  // ═══════════════════════════════════════════════════════════════
  // LIBRARY (shared media library)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/library/upload', 'post', op({
    tags: ['Library'],
    summary: 'Upload a file to the shared media library (multipart/form-data)',
    operationId: 'libraryUploadMultipart',
    requestBody: {
      required: true,
      content: {
        'multipart/form-data': {
          schema: {
            type: 'object',
            properties: {
              file: { type: 'string', format: 'binary' },
              zaloId: { type: 'string' },
              tags: { type: 'string' },
              folderId: { type: 'integer' },
            },
          },
        },
      },
    },
  }));
  addOp(paths, '/api/library/upload/json', 'post', op({
    tags: ['Library'],
    summary: 'Upload a file to the shared media library as base64 JSON (used by Employee mode instead of multipart)',
    operationId: 'libraryUploadJson',
    requestBody: requestBody({
      zaloId: { type: 'string' }, fileName: { type: 'string' }, mimeType: { type: 'string' },
      base64: { type: 'string' }, tags: { type: 'string' }, folderId: { type: 'integer' },
    }),
  }));
  addOp(paths, '/api/library/items', 'get', op({
    tags: ['Library'],
    summary: 'List media library items, paginated',
    operationId: 'getLibraryItems',
    parameters: [qp('zaloId', 'string', true), qp('page', 'integer'), qp('limit', 'integer'), qp('type'), qp('search'), qp('folderId', 'integer')],
  }));
  addOp(paths, '/api/library/item/{uuid}', 'get', op({
    tags: ['Library'],
    summary: 'Get a single media library item by uuid',
    operationId: 'getLibraryItem',
    parameters: [pp('uuid')],
  }));
  addOp(paths, '/api/library/item/{uuid}', 'patch', op({
    tags: ['Library'],
    summary: 'Update a media library item\'s metadata',
    operationId: 'updateLibraryItem',
    parameters: [pp('uuid')],
    requestBody: requestBody({}, false),
  }));
  addOp(paths, '/api/library/item/{uuid}', 'delete', op({
    tags: ['Library'],
    summary: 'Delete a media library item',
    operationId: 'deleteLibraryItem',
    parameters: [pp('uuid')],
  }));
  addOp(paths, '/api/library/folders', 'get', op({
    tags: ['Library'],
    summary: 'List media library folders for an account',
    operationId: 'getLibraryFolders',
    parameters: [qp('zaloId', 'string', true), qp('type')],
  }));
  addOp(paths, '/api/library/folders', 'post', op({
    tags: ['Library'],
    summary: 'Create a media library folder',
    operationId: 'createLibraryFolder',
    requestBody: requestBody({ zaloId: { type: 'string' }, name: { type: 'string' }, parentId: { type: 'integer' }, color: { type: 'string' }, type: { type: 'string' } }),
  }));
  addOp(paths, '/api/library/folders/{id}', 'delete', op({
    tags: ['Library'],
    summary: 'Delete a media library folder',
    operationId: 'deleteLibraryFolder',
    parameters: [pp('id', 'integer')],
  }));
  addOp(paths, '/api/library/file/{uuid}', 'get', op({
    tags: ['Library'],
    summary: 'Serve the original file of a media library item (unauthenticated — tunnel security only)',
    operationId: 'serveLibraryFile',
    security: NO_SECURITY,
    parameters: [pp('uuid')],
  }));
  addOp(paths, '/api/library/thumb/{uuid}', 'get', op({
    tags: ['Library'],
    summary: 'Serve the thumbnail of a media library item (unauthenticated — tunnel security only)',
    operationId: 'serveLibraryThumb',
    security: NO_SECURITY,
    parameters: [pp('uuid')],
  }));

  // ═══════════════════════════════════════════════════════════════
  // MEDIA (relayed message attachments — distinct from the Library above)
  // ═══════════════════════════════════════════════════════════════

  addOp(paths, '/api/media/{mediaPath}', 'get', op({
    tags: ['Media'],
    summary: "Serve a relayed message attachment / thumbnail / avatar file by relative path (unauthenticated — tunnel security only). Supports HTTP Range for video. Path shapes: '{zaloId}/{date}/{filename}', 'thumb/{zaloId}/{date}/{filename}', 'avatar/{zaloId}/{filename}'",
    operationId: 'serveMediaFile',
    security: NO_SECURITY,
    parameters: [pp('mediaPath', 'string', 'Catch-all relative path under the media base directory')],
  }));

  return paths;
})();

export const generatedTags: Array<{ name: string; description?: string }> = [
  { name: 'Boot', description: 'Initial bootstrap data for a newly connected employee' },
  { name: 'Conversations', description: 'Conversations/contacts — read, flags, alias, profile, delete, pin' },
  { name: 'Messages', description: 'Chat messages — read, search, mark read/recalled, delete, reactions, pins' },
  { name: 'Search', description: 'Full-text search over messages' },
  { name: 'Friends', description: 'Friend list management' },
  { name: 'FriendRequests', description: 'Sent/received friend request management' },
  { name: 'Groups', description: 'Group membership queries and mutations' },
  { name: 'CRM', description: 'CRM notes, campaigns, tags, contacts, activity stats, send log, queue status' },
  { name: 'Labels', description: 'Local (per-Boss) conversation labels and thread assignments' },
  { name: 'QuickMessages', description: 'Saved quick-reply messages' },
  { name: 'Drafts', description: 'Per-thread message drafts' },
  { name: 'Links', description: 'Shared links extracted from messages' },
  { name: 'Settings', description: 'App settings key/value store, including notification settings' },
  { name: 'Stickers', description: 'Sticker packs, recent stickers, keyword mappings' },
  { name: 'BankCards', description: 'Saved bank card info' },
  { name: 'Proxies', description: 'Proxy pool configuration and per-account assignment' },
  { name: 'ERP-Tasks', description: 'ERP task and project management' },
  { name: 'ERP-HRM', description: 'ERP departments, positions, employee profiles' },
  { name: 'ERP-Calendar', description: 'ERP calendar events' },
  { name: 'Analytics', description: 'Dashboard and analytics metrics' },
  { name: 'Workflow', description: 'Visual automation workflow CRUD and run logs' },
  { name: 'Integrations', description: 'Third-party integration (POS/payment/shipping) configuration' },
  { name: 'AI', description: 'AI assistant configuration, chat/suggest proxying, and usage analytics' },
  { name: 'Library', description: 'Shared media library (images/files/videos) across accounts' },
  { name: 'Media', description: 'Relayed message attachment file serving' },
];
